### ISSUE TITLE
good！！！

### ISSUE THREAD

**Issue by hzyyy** [BingKui/javascript-zh#2]
虽然敲代码的时间不长，但是有一颗‘敲出优雅代码’的心，全是满满的干货；对应自己平时的开发习惯，部分是规范的，部分需要改正的。

**Comment by BingKui** [comment]
- 对于个人来说，规范只是一种建议，不一定是最好的，也不一定适合自己，关键还要自己敲的舒服，毕竟**自己爽才是真的爽！！！**
- 对于团队来说，一个公认的规范，对于代码质量的提升和团队协作是有很大帮助的！！！毕竟谁都不想看:hankey:一样的代码！！！
